{% set name = "enumlib" %}
{% set version = "2.0.6" %}
{% set symlibver = "1f821512c42b1564893beb2a784451ace1ebfd01" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - fn: enumlib.tar.gz
    url: https://github.com/msg-byu/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: d6318c202b8b50c6b93c4d91fedaa8e6f97c97a4734605b5d2e14c9bc5e360c9
    patches:
      - make.patch
  - fn: symlib.tar.gz
    url: https://github.com/msg-byu/symlib/archive/{{ symlibver }}.tar.gz
    sha256: b368b92f3adceac4f4fc04d893c9220529651c26d8f6c4245acf5f80531c7244
    folder: symlib
    patches:
      - symlib.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('fortran') }}

test:
  files:
    - struct_enum.in.fcc
  commands:
    - enum.x struct_enum.in.fcc

about:
  home: https://github.com/msg-byu/enumlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Enumeration library for generating derivative structures.
  description: |
    This code generates the derivative superstructures of a parent lattice.
    It works for general lattices, including "multilattices," like HCP, which
    have more than one lattice point in the unit cell. The code can enumerate
    over all concentrations or in a restricted concentration range.
  doc_url: https://github.com/msg-byu/enumlib
  dev_url: https://github.com/msg-byu/enumlib

extra:
  recipe-maintainers:
    - jan-janssen
